### ISSUE TITLE
Listar proposições votadas em plenário

### ISSUE THREAD

**Issue by lucasoshiro** [CamaraDosDeputados/dados-abertos#187]
Oi,
Eu estou trabalhando em um projeto que utilizava a API antiga da câmara, e ele depende muito do método ListarProposiçõesVotadasEmPlenario, que permitia procurar proposições que sofreram votação em plenário em determinado ano.
Meu grupo está portando o projeto para a API nova, mas não encontramos nenhum método que forneça a mesma funcionalidade que este. Existe alguma forma de conseguir esses dados?

**Comment by CeninCD** [comment]
Salve, Lucas!

A funcionalidade está prevista para o fatídico e infame _endpoint_ `/votacoes`, tão demandado e tão problemático.

Se os problemas do _webservice_ `ListarProposicoesVotadasEmPlenario` não forem impeditivos para o seu projeto, continue usando-o sem medo. Não prevemos tirá-lo do ar tão cedo.

Nós ainda não implementamos o `/votacoes` porque queremos eliminar esses problemas e isso exige que a área responsável pelas bases de dados faça uma série de correções. De toda forma, as estruturas de dados previstas na nova API são bem diferentes das anteriores. Quando você fala em "funcionalidades", você se refere a algumas informações específicas que são fornecidas pelo _webservice_?

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara
