### ISSUE TITLE
Endpoint ObterInteiroTeorDiscursosPlenario retornando erro

### ISSUE THREAD

**Issue by gacra** [CamaraDosDeputados/dados-abertos#196]
O endopoint ObterInteiroTeorDiscursosPlenario da API antiga está retornando o erro `Tipo orgaos nao encontrados.` ao pesquisar por discursos mais recentes (do último mês, pelo menos) mesmo que os parâmetros estejam corretos.
Por exemplo a busca (discurso de VICENTINHO JÚNIOR de 28/11/2018 17:20:00):
http://www.camara.leg.br/SitCamaraWS/SessoesReunioes.asmx/obterInteiroTeorDiscursosPlenario?codSessao=249.2018&numOrador=5&numQuarto=45240&numInsercao=5

**Comment by CeninCD** [comment]
Salve, Guilherme!

Provavelmente o Caio está certo. Houve uma atualização no sistema de registro de discursos que mudou algumas coisas na base de dados e não fomos avisados sobre essas alterações. Vamos dar uma olhada no que houve.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by gacra** [comment]
Valeu, Fabricio.

Fico no aguardo.

**Comment by gacra** [comment]
Olá, @CeninCD , houve algum avanço na resolução desse bug?

**Comment by EquipeDadosAbertosCD** [comment]
Ei, Guilherme, beleza?

Conferindo algumas coisas aqui. Esse problema _deveria_ ter sido resolvido depois de um ajuste feito na base de dados. Você sabe se voltou a ocorrer?

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by gacra** [comment]
Fala, Fabricio, tudo certo e você?

Foi resolvido mesmo, não voltou mais a acontecer.

Obrigado!
