### ISSUE TITLE
Endpoint ObterAndamento retornando erro 500

### ISSUE THREAD

**Issue by gacra** [CamaraDosDeputados/dados-abertos#224]
Olá, para algumas proposições, o endpoint `ObterAndamento` da API antiga está retornando erro `500` e a seguinte mensagem:

```
Conversion from type &#39;DBNull&#39; to type &#39;String&#39; is not valid. - Microsoft.VisualBasic -    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at CamaraWSSemComponente.Orgaos.ObterAndamento(String sigla, Int32 numero, Int32 ano, String dataIni, String codOrgao)
``` 

Alguns exemplos são:

https://www.camara.leg.br/SitCamaraWS/Orgaos.asmx/ObterAndamento?sigla=PL&numero=3536&ano=2012&dataIni=&codOrgao=

https://www.camara.leg.br/SitCamaraWS/Orgaos.asmx/ObterAndamento?sigla=PL&numero=10557&ano=2018&dataIni=&codOrgao=

https://www.camara.leg.br/SitCamaraWS/Orgaos.asmx/ObterAndamento?sigla=PL&numero=6160&ano=2016&dataIni=&codOrgao=

**Comment by CeninCD** [comment]
Salve, Acra!

Obrigado pelo aviso. Estamos investigando. Vimos que algumas proposições causam esse erro, mas ainda não descobrimos o que faz com que algumas sejam corretamente retornadas.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by gacra** [comment]
Valeu Fabricio! Fico no aguardo.

**Comment by gacra** [comment]
Olá Fabricio,

entrei nos links que enviei e verifiquei que agora eles estão funcionando. Entretanto, nesses exemplos, sempre tem uma tramitação sem `ordemDeTramitacao` (o que talvez fosse até o que estava causando o problema, imagino).

É possível uma tramitação não ter ordem? Pois, como foi dito ontem, nós aqui consideramos que esse campo nunca vinha vazio e usamos esse dado para criar o identificador da tramitação em nosso sistema.

**Comment by CeninCD** [comment]
Salve, Guilherme!

Descobrimos o problema, que estava causando um questionamento diferente também por usuários da API nova.

Exatamente 16 proposições na base de dados -- entre elas, as dos links que você enviou --  tiveram alguma tramitação do tipo "encerramento de prazo para emendas" cadastrada sem um número de ordem, que no _webservice _ `ObterAndamento` é retornado com o nome `<ordemDeTramitacao>` e na API nova é o campo `sequencia` da resposta de `/proposicoes/{id}/tramitacoes`.

Isto é: o _webservice_ voltou a funcionar, mas você vai ver que em um dos itens retornados o campo `<ordemDeTramitacao>` está vazio. O código não estava preparado para a possibilidade de esse campo estar vazio, e corrigimos esse tratamento.

Mas a ausência do dado em si é um problema que depende de atuação da área de negócio. Todos esses registros foram criados em 31/01/2019, e existem 78.667 registros de tramitação com o mesmo tipo que não têm esse campo vazio -- ou seja, há indícios de que houve um problema localizado e pontual de cadastramento da informação. Já enviei um questionamento às áreas responsáveis por isso, mas ainda não tivemos resposta.

Mais uma vez, obrigado por avisar! Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by gacra** [comment]
Olá, @EquipeDadosAbertosCD 
Tava dando uma olhada aqui nas issues, e creio que esta aqui já foi resolvida completamente, com os casos não retornando mais erro e com todas as tramitações com ordem (pelo que pude observar).

Valeu!
