### ISSUE TITLE
ERRO 500 - Deputado ID 141439

### ISSUE THREAD

**Issue by netoferraz** [CamaraDosDeputados/dados-abertos#236]
URL da request: `https://dadosabertos.camara.leg.br/api/v2/deputados/141439/discursos?idLegislatura=56&ordenarPor=dataHoraInicio&ordem=ASC`

**RETORNO**:  `{'status': 500, 'title': 'Erro no servidor', 'detail': 'Erro - Contate o Administrador', 'instance': None, 'code': 9}`

**Comment by vitormarcal** [comment]
Olá @netoferraz, tudo bem?
Havia um problema relacionado ao apostrofo no nome do deputado mas já resolvido.
Obrigado por reportar este problema! :D
