### ISSUE TITLE
CPF está missing na tabela deputados.csv

### ISSUE THREAD

**Issue by lucasmation** [CamaraDosDeputados/dados-abertos#245]
Há algum motivo para a variável `cpf` estar com todos os valores missing na tabela `deputados`?

Estou olhando pelo arquivo `deputados.csv`

**Comment by EquipeDadosAbertosCD** [comment]
Olá de novo, Lucas!

Existe sim: o [Ato da Mesa 45/2012](https://www2.camara.leg.br/legin/int/atomes/2012/atodamesa-45-16-julho-2012-773823-normaatualizada-cd-mesa.doc), que regulamenta a aplicação da Lei de Acesso à Informação na Câmara.

Até novembro, o texto era explícito em listar o número de CPF entre as chamadas "informações pessoais", com "acesso restrito", salvo "previsão legal". Tudo no seu artigo 27.

Agora, para responder sua pergunta, descobri que houve em novembro uma alteração significativa nesse artigo, pelo [Ato da Mesa 246/2018](https://www2.camara.leg.br/legin/int/atomes/2018/atodamesa-246-21-novembro-2018-787382-publicacaooriginal-156825-cd-mesa.html). A menção ao CPF foi substituída por "_número de documentos de identificação pessoal_", mas, ao que me parece, a mudança em geral tornou o acesso aos dados ainda mais restrito.

Nossa recomendação a todos os usuários que consideram útil e importante a publicação do CPF no **Dados Abertos ** é registrar a demanda por meio do serviço [Fale Conosco da Câmara](https://camara.custhelp.com).

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by lucasmation** [comment]
Grato. Pedido feito (N protocolo 190527-000531). Fechando o issue por aqui por enquanto
