### ISSUE TITLE
Não é possível pegar a propriedade X-Total-Count no cabeçalho da requisição

### ISSUE THREAD

**Issue by dotsomething** [CamaraDosDeputados/dados-abertos#252]
Estou utilizando a biblioteca ``HttpClient`` do Angular 6. E ao tentar pegar a propriedade ``X-Total-Count`` percebi que não posso pegá-lo pois os cabeçalho não estão [expostos](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

Obrigado desde já!

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Victor!

Obrigado pelo contato e pela informação. Francamente, não tínhamos conhecimento sobre esse cabeçalho e sua necessidade em requisições CORS. Você é o primeiro usuário a falar disso!

Ao que parece, poderemos implementar isso rapidamente.

Obrigado mais uma vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by vitormarcal** [comment]
Olá, adicionamos o cabeçalho Access-Control-Expose-Headers com a lista de headers expostos.
