### ISSUE TITLE
Eventos: diferença entre Reunião e Sessão Deliberativa

### ISSUE THREAD

**Issue by lucasmation** [CamaraDosDeputados/dados-abertos#255]
Ola, 

uma dúvida sobre conteúdo (nao eh nada da API), mas tb nao encontrei nada sobre isso na internet. 

Nos eventos, qual e a direrença entre uma "reunião" e uma "seção" deliberativa?

Estou trabalhando com os arquivso eventos-*.csv. Para os dados de 2010 a 2019 tempos ~11mil "Reuniões Deliberativas" e 1786 "Sessões Deliberativas"

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Lucas!

"_Sessão_" é o termo regimental usado para as reuniões no Plenário. Nas comissões é usado o termo "_reunião_".

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by lucasmation** [comment]
Grato!
