### ISSUE TITLE
API retorna apenas um bloco

### ISSUE THREAD

**Issue by LucasAlegre** [CamaraDosDeputados/dados-abertos#261]
O request https://dadosabertos.camara.leg.br/api/v2/blocos?ordem=ASC&ordenarPor=nome está retornando apenas um bloco.

Obrigado,
Lucas

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Lucas!

Desculpe a demora na resposta. O _endpoint_ sem parâmetros está retornando um só bloco porque, de fato, só há um bloco em atividade no momento.

Para obter todos os blocos que existiram na atual legislatura, use o parâmetro `idLegislatura=56`. Você pode usar mais de um número de legislatura nesse parâmetro, separando-os com vírgulas. Mas por enquanto só temos dados de blocos a partir da legislatura 54.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by LucasAlegre** [comment]
Muito obrigado!

Abraços,
Lucas
