### ISSUE TITLE
Despesas totais de um deputado em exercício

### ISSUE THREAD

**Issue by edgarpf** [CamaraDosDeputados/dados-abertos#262]
Olá, estou criando uma aplicação que irá mostrar uma tabela com todos os deputados em exercício e o total de suas despesas em seu mandado atual até a data presente. Irei ordenar os deputados por gastos. A Idéia é exibir em destaque os deputados que menos gastam.

Atualmente é possível fazer um **GET** em **/deputados/{id}/despesas?idLegislatura=X** para obter as despesas de um deputado específico mas nesse caso tenho que fazer uma enorme quantidade de requisições para pegar TODAS as despesas de TODOS deputados. 

Sugiro a criação de um novo Endpoint: **/deputados/{idLegislatura}/despesasTotais**

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Edgar!

Desculpe a demora na resposta. Tivemos severas alterações na equipe nos últimos dias e as comunicações ficaram emboladas por aqui.

Para esse tipo de aplicação que você mencionou, o recomendado é que você use os arquivos para download disponíveis em https://dadosabertos.camara.leg.br/swagger/api.html#staticfile . TODAS as despesas de TODOS os deputados, desde 2008, em apenas 12 requisições, com atualização diária e, de quebra, dados comprimidos em ZIP.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by edgarpf** [comment]
Consegui contornar a situação fazendo um scrapper nas páginas de cada deputado. 
O resultado pode ser conferido aqui: https://github.com/edgarpf/gastos-deputados-federais

**Comment by oGabrielArruda** [comment]
> Olá, Edgar!
> 
> Desculpe a demora na resposta. Tivemos severas alterações na equipe nos últimos dias e as comunicações ficaram emboladas por aqui.
> 
> Para esse tipo de aplicação que você mencionou, o recomendado é que você use os arquivos para download disponíveis em https://dadosabertos.camara.leg.br/swagger/api.html#staticfile . TODAS as despesas de TODOS os deputados, desde 2008, em apenas 12 requisições, com atualização diária e, de quebra, dados comprimidos em ZIP.
> 
> Abraço!
> 
> Fabricio Rocha
> Equipe Dados Abertos - Câmara

Fabricio, uma dúvida: os dados das rotas de despesa são atualizadas na mesma medida em que os arquivos são atualizados ou não?

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Gabriel!

Sim. A API e os arquivos usam exatamente a mesma tabela da mesma base de dados. Os arquivos são gerados uma vez por dia, a cada madrugada, e por isso têm todos os dados que você conseguia obter pela API no dia anterior.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
