### ISSUE TITLE
Erro 500 na rota /eventos com dataInicial e dataFinal

### ISSUE THREAD

**Issue by brosquinha** [CamaraDosDeputados/dados-abertos#265]
Olá,

Estou tomando erro 500 na rota `/eventos` quando envio `dataInicio` e `dataFim`. Não sei se há relação com a atualização dessa rota enviada nessa semana... aqui está um [exemplo de solicitação](https://dadosabertos.camara.leg.br/api/v2/eventos?dataInicio=2019-07-20&dataFim=2019-07-27).

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Thales!

Obrigado pelo registro. O problema foi confirmado e já conseguimos localizar uma possível causa. Ainda nesta segunda-feira deveremos publicar a correção em um novo build.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Thales!

Acabamos nos atrasando, mas está no ar a atualização que pode ter resolvido o problema. Você gostaria de fazer uns testes?

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by brosquinha** [comment]
Opa, rodei meus testes e está funcionando, sim! Valeu! :+1:
