### ISSUE TITLE
Dados incorretos do Gabinete do Deputado em api/v2/deputados/

### ISSUE THREAD

**Issue by gleitebsb** [CamaraDosDeputados/dados-abertos#266]
Prezados,

Ao consultar os dados do deputado 73433, verifiquei que a Tag <predio> está com valor "x", então verifiquei no endereço "https://www.camara.leg.br/deputados/73433" e lá consta que o endereço é: " Gabinete 4 - Ed. principal - Câmara dos Deputados" e na versão antiga da API consta como 
`<anexo>1</anexo>.` 
 
`<xml>`
`<dados>`
`<id>73433</id>`
`<uri>`
`https://dadosabertos.camara.leg.br/api/v2/deputados/73433`
`</uri>`
`<nomeCivil>ARLINDO` CHIGNALIA JUNIOR</nomeCivil>
`<ultimoStatus>`
`<id>73433</id>`
`<uri>`
`https://dadosabertos.camara.leg.br/api/v2/deputados/73433`
`</uri>`
`<nome>ARLINDO` CHINAGLIA</nome>
`<siglaPartido>PT</siglaPartido>`
`<uriPartido>`
`https://dadosabertos.camara.leg.br/api/v2/partidos/36844`
`</uriPartido>`
`<siglaUf>SP</siglaUf>`
`<idLegislatura>56</idLegislatura>`
`<urlFoto>`
`https://www.camara.leg.br/internet/deputado/bandep/73433.jpg`
`</urlFoto>`
`<data>2019-02-01T11:45</data>`
`<nomeEleitoral>ARLINDO` CHINAGLIA</nomeEleitoral>
`<gabinete>`
`<nome>004</nome>`
`<predio>x</predio>`
`<sala>004</sala>`
`<andar/>`
`<telefone>3215-5966</telefone>`
`<email>dep.arlindochinaglia@camara.leg.br</email>`
`</gabinete>`
`<situacao>Exercício</situacao>`
`<condicaoEleitoral>Titular</condicaoEleitoral>`
`<descricaoStatus/>`
`</ultimoStatus>`
`<cpf>06821146187</cpf>`
`<sexo>M</sexo>`
`<urlWebsite/>`
`<redeSocial/>`
`<dataNascimento>1949-12-24</dataNascimento>`
`<dataFalecimento/>`
`<ufNascimento>SP</ufNascimento>`
`<municipioNascimento>Serra` Azul</municipioNascimento>
`<escolaridade>Pós-Graduação</escolaridade>`
`</dados>`
`<links>`
`<link>`
`<rel>self</rel>`
`<href>`
`https://dadosabertos.camara.leg.br/api/v2/deputados/73433`
`</href>`
`</link>`
`</links>`
`</xml>``

**Comment by EquipeDadosAbertosCD** [comment]
Salve, gleitebsb!

A informação do Portal da Câmara está correta. O gabinete do dep. Chinaglia fica mesmo no edifício principal.

A informação fornecida pela versão antiga da API está errada, porque na Câmara existe mesmo um Anexo 1, e não é nele que fica o gabinete. Vou repassar a sua reclamação à área que agora ficou responsável pela manutenção desses webservices.

Na base de dados da qual a nova API do Dados Abertos obtém a informação do gabinete, o edifício principal é realmente identificado com o número de anexo "_x_". Devo admitir que eu mesmo não havia percebido isso (são bem poucos os deputados com gabinetes no prédio principal; apenas alguns ex-presidentes da Câmara). Não está errado, mas é feio pacas. Acho que ficaria melhor deixar o campo vazio.

Obrigado pelo aviso e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
