### ISSUE TITLE
Json de órgãos errado

### ISSUE THREAD

**Issue by jairNeto** [CamaraDosDeputados/dados-abertos#270]
O objeto retornado pela chamada https://dadosabertos.camara.leg.br/arquivos/orgaos/json/orgaos.json
está finalizando em uma vírgula.
Este é o final do objeto retornado:
},
    {
      "uri": "https://dadosabertos.camara.leg.br/api/v2/orgaos/6003",
      "sigla": "PEC57402",
      "apelido": "PEC 574/02 - PERCENTUAL DESPESAS LEGISL. MUNICIPAL",
      "nome": "Comissão Especial destinada a apreciar e proferir parecer à Proposta de Emenda à Constituição nº 574-A, de 2002, que \"altera   a   redação  do  art.  29-A  da Constituição Federal\", estabelecendo que o total de despesa do Poder Legislativo Municipal não poderá ultrapassar os percentuais já fixados relativos à receita corrente líquida do Município, definida em lei complementar.",
      "codTipoOrgao": 3,
      "tipoOrgao": "Comissão Especial",
      "dataInicio": "2003-05-19T00:00:00",
      "dataInstalacao": "2003-09-02T00:00:00",
      "dataFim": "2004-06-29T00:00:00",

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Jair!

Nós descobrimos que houve um problema de espaço de armazenamento em um dos servidores em que ficam arquivos gerados pelo Dados Abertos. Os arquivos para download foram gerados novamente, o que deve ter resolvido o problema que você apontou, e estamos investigando causas e precauções possíveis. Seu alerta foi fundamental para descobrirmos o problema.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
