### ISSUE TITLE
Como alterar endereço de e-mail na conta do eSIC?

### ISSUE THREAD

**Issue by cuducos** [CamaraDosDeputados/dados-abertos#274]
Boa tarde,

Ao efetuar o login, na página [_Minha conta_](https://camara.custhelp.com/app/account/profile) não há a opção de atualizar o endereço de e-mail. Como fazemos para mudar o endereço de e-mail?

Muito obrigado,

> **Observação**
> O link não é para um domínio da Câmara pois a Câmara utiliza o _Oracle Service Cloud Support_ para o set eSIC. Isso fica claro no domínio `camara.custhelp.com` a que somos direcionados quando efetuamos o login no link _Fale Conosco_ que consta nas páginas `camara.leg.br`.

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Cuducos!

Encaminhei sua dúvida ao pessoal da área técnica do sistema. Obtive hoje (segunda) a resposta de que não há mesmo uma maneira de o próprio usuário alterar seu e-mail de cadastro. A recomendação dada é de você encaminhar o pedido de alteração pelo próprio Fale Conosco online ou pelo telefone de atendimento 0800-619-619.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by cuducos** [comment]
Muito obrigado, Fabricio.
Resolvido dessa forma então : )
