### ISSUE TITLE
Dados sobre votações nomimais em proposições

### ISSUE THREAD

**Issue by reichaves** [CamaraDosDeputados/dados-abertos#278]
Olá
Por favor, consultei os tipos de informações na API (https://dadosabertos.camara.leg.br/swagger/api.html#api) e não encontrei como obter dados sobre votações de proposições - como cada parlamentar votou em uma proposição

Este item foi retirado da API?

**Comment by RodrigoMenegat** [comment]
Reinaldo, esses dados só estão disponíveis na api antiga. A nova retornava
valores inconstantes.

Em sex, 20 de dez de 2019 13:12, Reinaldo Chaves <notifications@github.com>
escreveu:

**Comment by reichaves** [comment]
Perfeito, obrigado
Encontrei aqui: https://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/obtervotacaoproposicao
