### ISSUE TITLE
Cabeçalho HTTP Retry-After com valor inválido

### ISSUE THREAD

**Issue by brosquinha** [CamaraDosDeputados/dados-abertos#286]
Olá,

Algumas vezes, o cabeçalho HTTP Retry-After é devolvido pela API com um valor `30s`. A [RFC7231](https://tools.ietf.org/html/rfc7231#section-7.1.3) recomenda que esse valor seja ou uma data de formato específico ou um número inteiro não-negativo. Para uma melhor integração com clientes HTTP por aí que esperam esse comportamento desse cabeçalho, o ideal seria que fosse, portanto, alterado o valor retornado pela API para apenas `30` (removendo o `s` do final).

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Thales!

Obrigado pelo aviso -- bem observado e corretíssimo. A configuração do servidor já foi alterada.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
