### ISSUE TITLE
Falha ao acessar o Swagger

### ISSUE THREAD

**Issue by Otoru** [CamaraDosDeputados/dados-abertos#288]
Ao acessar a página que contem o swagger da API, o mesmo não é exibido e tenho os seguintes erros no console:

```
vendor.js:1 Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
dadosabertos.min.js:1 Uncaught ReferenceError: $ is not defined at dadosabertos.min.js:1
api.html:865 Uncaught ReferenceError: SwaggerUIBundle is not defined at window.onload (api.html:865)
```
Oque pode ser isso?

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Vitor!

Obrigado pelo contato. Não estou conseguindo reproduzir o problema. A página foi exibida como esperado no Firefox e no Chrome. Você poderia testar novamente e, caso o problema se repita, enviar o que mais tiver de informações sobre versão de browser, URL utilizada, etc?

Abraço e obrigado outra vez!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by Otoru** [comment]
Bom dia Fabricio,

Obrigado pelo retorno. Na noite de hoje fui testar e o comportamento estava normalizado.
