### ISSUE TITLE
Sugestão: comunidade de Dados Abertos no Telegram

### ISSUE THREAD

**Issue by jedibruno** [CamaraDosDeputados/dados-abertos#290]
Aproveitando que o espaço do Dados Abertos sugere a comunidade criada no whatsapp, gostaria de sugerir a inclusão de sugestão da comunidade "Dados Abertos BR" no Telegram (https://t.me/dadosabertos). 

A comunidade possui mais de 1600 membros e é destinada ao compartilhamento de informações, conjuntos de dados e discussões sobre Dados Abertos em todo o país.

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Bruno!

Você está sugerindo que seja incluído o grupo do Telegram no READ.me do repositório aqui no GitHub, é isso?

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by jedibruno** [comment]
Oi, Fabricio!

Sim, é isso mesmo! Acho que o pessoal vai encontrar discussões e conteúdos bem bacanas sobre dados abertos por lá também.

Abraço!

**Comment by EquipeDadosAbertosCD** [comment]
Atendido! Obrigado pela sugestão!

Fabricio Rocha
Equipe Dados Abertos - Câmara
