### ISSUE TITLE
Referência para o código do tipo de autor está indisponível

### ISSUE THREAD

**Issue by BordaLorde** [CamaraDosDeputados/dados-abertos#293]
Prezados, 

Quando fiz uma requisição no seguinte endpoint a fim de obter o autor de uma determinada proposição:
 `https://dadosabertos.camara.leg.br/api/v2/proposicoes/{id_da_proposição}/autores` 

É retornado um campo chamado `codTipo` que por dedução pude perceber que é usado para diferenciar os diversos tipos de autores de proposições. Porém, não consegui achar na lista de endpoints de referência um em específico que retornasse todos os códigos disponíveis e seus significados. Também não achei documentação que esclarecesse esses tipos e o que significam.

Se fosse possível disponibilizar algum meio de sabermos o significado desses códigos, facilitaria o desenvolvimento em cima da API, visto que não seria mais necessário deduzir o que cada codigo representa.

Obrigado desde já

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Samuel!

Realmente, não publicamos até agora um devido endpoint `/referencias/proposicoes/codTipoAutor`. Falha nossa.

Mas pode lhe atender de imediato a informação de que deputados são identificados com o _codTipoAutor_ 10000 e senadores com o _codTipoAutor_ 20000. Além desses valores, a lista de tipos de autores disponível na base é toda e exatamente a mesma lista que pode ser obtida em `/referencias/orgaos/codTipoOrgao`. 

Espero que isso já te ajude. De toda forma, vamos trabalhar na publicação desse endpoint faltante.

Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by EquipeDadosAbertosCD** [comment]
Ei, Samuel!

Colocamos o endpoint no ar na segunda-feira. Valeu!

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by BordaLorde** [comment]
Muito obrigado. Abraço!
