### ISSUE TITLE
Orientacoes vazias

### ISSUE THREAD

**Issue by flaviolenz** [CamaraDosDeputados/dados-abertos#297]
Nessa votacao do Destaque 2 da PEC10/2020:
https://www.camara.leg.br/presenca-comissoes/votacao-portal?reuniao=59597
https://dadosabertos.camara.leg.br/api/v2/votacoes/2249946-99

Nao estao retornando as orientacoes, nem os votos:
https://dadosabertos.camara.leg.br/api/v2/votacoes/2249946-99/orientacoes
https://dadosabertos.camara.leg.br/api/v2/votacoes/2249946-99/votos

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Flávio!

Os dados da votação ainda não foram copiados para a base onde podemos acessá-los. Os últimos dados registrados na tabela de votos nominais são da sessão de 05/05, com _idEvento_ 59596.

Estamos colocando em produção agora à tarde (sexta, 08/05) uma atualização de consultas para buscar, na base do sistema que está sendo usado para cadastrar as votações virtuais, os dados de orientação dos partidos. Infelizmente, só há como extrairmos os dados referentes a votações nominais.

Vou entrar em contato com os gestores desse sistema para averiguar se está havendo um problema com a rotina de cópia dos votos nominais de uma base para a outra. Obrigado pelo aviso.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by flaviolenz** [comment]
Opa Fabricio,

Obrigado pelo retorno.
Amigo, estou fazendo uma ferramenta que troca msg de Whatsapp com os deputados dando informacoes sobre as proposicoes.
As orientacoes era o que mais importava, na verdade.
Achei que a API respondia com dados on-line.

Alguma alternativa?
(se nao houver, vou extrair dos HTML do site)

**Comment by EquipeDadosAbertosCD** [comment]
Salve, Flavio!

O endpoint da API com as orientações já foi atualizado. Verifique aí se ele corresponde ao que você precisa.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by flaviolenz** [comment]
opa. maravilha.
agora está vindo.

há um delay de quanto tempo pra o dado estar disponivel na API?

**Comment by EquipeDadosAbertosCD** [comment]
Olá de novo, Flavio!

A API disponibiliza a cada acesso o que estiver nas bases de dados que são alimentadas pelas aplicações internas da Câmara. É tempo real, portanto -- no que depende de tecnologia. Mas temos percebido problemas em relação a esses dados das votações virtuais porque os dados do sistema utilizado para elas não têm sido copiados para as bases com a regularidade habitual. Tenho mantido contato com a equipe que cuida desse sistema para que isso seja resolvido em definitivo.

Abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by flaviolenz** [comment]
Olá Fabricio,

Gostaria de dar uma sugestao para economizar nas chamadas aos end-points.
Que os objetos referenciados viessem mais preenchidos.

Por exemplo:
https://dadosabertos.camara.leg.br/api/v2/eventos/60754/pauta

retorna uma lista de itens que podem ter uma proposicao atrelada:
```
<pauta>
<regime>Ordinária (Art. 151, III, RICD)</regime>
<codRegime>14</codRegime>
<ordem>5</ordem>
<proposicao_>
<id>1514151</id>
<uri>https://dadosabertos.camara.leg.br/api/v2/proposicoes/1514151</uri>
<siglaTipo>PL</siglaTipo>
<codTipo>139</codTipo>
<numero>2021</numero>
<ano>2015</ano>
<ementa>Condiciona a realização de entrevistas ou exibição de imagens de presos sob custódia do Estado no interior de delegacias ou estabelecimentos prisionais à prévia autorização judicial.</ementa>
</proposicao_>
<uriProposicaoRelacionada/>
<situacaoItem>Vista concedida</situacaoItem>
<uriVotacao/>
</pauta>
```

E vou exibir o resultado isso numa lista (com 40 itens, por exemplo), mas o normal de um PL eh que ele seja mencionado juntamente com o(s) autor(es).
Quando a consulta eh sobre 1 só proposicao, até que nao é muito prejuízo fazer uma chamada adicional pra pegar os autores, mas 40 chamadas adicionais é bem caro.
Da mesma forma, quero saber quem é o ultimo relator da materia (aí tenho que fazer uma chamada a /proposicoes pra pegar essa informacao).
E, se quero colocar o partido do autor, isso significa mais uma chamada pro endpoint /deputado pra cada um dos deputados, pq o endpoint /proposicao/9999/autores nao tras a informacao de partido.

Pra mostrar a pauta da CTASP dessa semana, foram essas chamadas:
```
https://dadosabertos.camara.leg.br/api/v2/eventos/60771  x1   (dados da reuniao)
https://dadosabertos.camara.leg.br/api/v2/eventos/60771/pauta  (retorna 42 itens em pauta)
https://dadosabertos.camara.leg.br/api/v2/proposicoes/99999   x42 (pra pegar os dados de cada proposicao))
https://dadosabertos.camara.leg.br/api/v2/proposicoes/99999/autores   x42 (pra pegar o primeiro autor das proposicoes)
https://dadosabertos.camara.leg.br/api/v2/deputados/99999   x42 (pra pegar o partido do primeiro autor)
https://dadosabertos.camara.leg.br/api/v2/proposicoes/99999/autores   x42 (pra pegar o primeiro autor das proposicoes)
https://dadosabertos.camara.leg.br/api/v2/deputados/99999 x33 itens que sao PL - pra pegar o Relator

```
Resumindo, foram 286 chamadas.





Isso ai foi so um exemplo, mas acho que tem varios pontos que os endpoints poderiam penetrar um pouco mais nos dados.
Uma coisa eh acessar uma base SQL, como deve estar sendo feito aí.. outra eh ficar fazendo chamadas HTTP.

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Flávio! Movido para o novo issue #309 .
