### ISSUE TITLE
Horário das Atualizações Diárias

### ISSUE THREAD

**Issue by matheushm** [CamaraDosDeputados/dados-abertos#305]
Olá, boa tarde!

Estou utilizando os arquivos diários de proposições, proposiçõesAutores e proposiçõesTemas.
Queria saber qual a rotina de atualização dos mesmos. Estou desenhando uma pipeline e queria uma expectativa de qual horário esses arquivos são diariamente atualizados.

Vocês sabem me informar?

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Matheus!

Todos os arquivos são gerados a partir de 1h da manhã. Como pode haver indisponibilidades temporárias de conexão ao banco de dados, não seria muito preciso dizer horários exatos para a geração de cada conjunto, mas em geral por volta de 05h30 todos os conjuntos de arquivos já estão prontos, e você pode programar seus scripts para buscá-los ao alvorecer do dia :grinning:

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by matheushm** [comment]
Obrigado!
