### ISSUE TITLE
Nenhum dados em discursos de deputado deputados/{id}/discursos

### ISSUE THREAD

**Issue by anhaabaete** [CamaraDosDeputados/dados-abertos#314]
Discursos não aparecem no serviço

exemplo:
https://dadosabertos.camara.leg.br/api/v2/deputados/92346/discursos

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Tiago!

Obrigado pelo aviso. De fato a chamada a esta URL que você passou resulta em lista vazia. Mas outros testes com diferentes _{id}_ mostraram que o endpoint está, sim, retornando os discursos que os deputados em atividade parlamentar tenham feito nos sete dias anteriores (período padrão quando não são usados os parâmetros _dataInicio_ e/ou _dataFim_). Por exemplo:

https://dadosabertos.camara.leg.br/api/v2/deputados/74784/discursos
https://dadosabertos.camara.leg.br/api/v2/deputados/160511/discursos
https://dadosabertos.camara.leg.br/api/v2/deputados/74848/discursos?dataInicio=2021-09-01
https://dadosabertos.camara.leg.br/api/v2/deputados/152605/discursos
https://dadosabertos.camara.leg.br/api/v2/deputados/74398/discursos
https://dadosabertos.camara.leg.br/api/v2/deputados/178927/discursos


Obrigado e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by anhaabaete** [comment]
Mas qual o motivo de ficar apenas 7 dias. Não é dados abertos?
tem que puxar por dada então? Não entendi.

**Comment by anhaabaete** [comment]
Vi aqui que precisa informar a data, obrigado
