### ISSUE TITLE
/partidos/{id}/membros

### ISSUE THREAD

**Issue by ferreira-tb** [CamaraDosDeputados/dados-abertos#324]
Há alguns problemas com os parâmetros nesse endpoint. As buscas são bem sucedidas, mas eles não geram o efeito esperado.

- Não é possível ordenar a lista de membros do partido usando `id`, `nome` ou `siglaUf`. OBS.: a ordem padrão parece ser `nome`, de maneira ascendente, então, nesse caso, é necessário usar descendente para observar o problema.
- Especificar uma quantidade de itens a serem exibidos também não produz qualquer efeito.

Exemplo de URL testada: `https://dadosabertos.camara.leg.br/api/v2/partidos/36899/membros?ordenarPor=siglaUf&ordem=asc&itens=17`

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Ferreira!

Obrigado pelo aviso e pela observação. A ordenação realmente não está funcionando como deveria. Abraço!

Fabricio Rocha
DITEC/SOCIT/SISEI+SEMID
Equipe Dados Abertos - Câmara
