### ISSUE TITLE
Error SSL

### ISSUE THREAD

**Issue by omartins-zs** [CamaraDosDeputados/dados-abertos#331]
Como posso resolver esse erro, teve alguma atualização que agora precise de SSL para funcionar ?

![image](https://user-images.githubusercontent.com/65038297/218777085-36f18c35-0a64-4a9c-b350-33d452289f5a.png)

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Gabriel!

Primeiro, desculpe pela demora na resposta. 

Não sei se você continua tendo problemas de acesso, mas na semana retrasada estive com o pessoal de infraestrutura da nossa TI para verificar o problema que você relatou.

No que pudemos verificar, o que pareceu mais provável é que a sua aplicação poderia estar usando certificados já expirados. O certificado usado pela Câmara para acessos HTTPS externos é o da Let's Encrypt, largamente utilizado por toda a internet. No começo de fevereiro este certificado foi atualizado e é isso que pode ter disparado o erro na sua aplicação. Por favor, verifique como a sua aplicação usa certificados, os atualize para os mais recentes e observe se o problema continua.

Obrigado e abraço!

Fabricio Rocha
DITEC/SOCIT/SISEI+SEMID
Equipe Dados Abertos - Câmara

**Comment by omartins-zs** [comment]
Ola muito obrigado após as mudanças desativei as verificaçoes de SSL ao fazer requisiçao pelo CURL e deu certo muito obrigado por terem respondido
