### ISSUE TITLE
JSON/XML em consulta

### ISSUE THREAD

**Issue by relderdesigner** [CamaraDosDeputados/dados-abertos#335]
Olá pessoal, estamos fazendo a seguinte consulta, com essa URI:
https://dadosabertos.camara.leg.br/api/v2/deputados?idLegislatura=57&ordem=ASC&ordenarPor=nome

Quando consultamos com os parâmetros: idLegislatura, ordem e ordernarPor, a API retorna dados em JSON. Porém quando consultamos apenas para: ordem e ordernarPor a API retorna em XML.

Saberiam informar se está havendo algum tipo de manutenção ou mudança?

**Comment by EquipeDadosAbertosCD** [comment]
Olá, relder!

Obrigado pelo aviso. O formato de resposta só deveria mudar pela presença do cabeçalho _Accept_ ou do parâmetro de query string _formato_ na requisição. Pude confirmar o problema e já está na nossa fila de correções com urgência.

Obrigado mais uma vez e abraço!

Fabricio Rocha
Equipe Dados Abertos - Câmara
