### ISSUE TITLE
Em qual horário exatamente os dados disponíveis para download são atualizados?

### ISSUE THREAD

**Issue by Victoreisdavid** [CamaraDosDeputados/dados-abertos#339]
Olá! Eu tenho um projeto (https://fiscalizaja.com) que utiliza o serviço da câmara, mais especificamente, baixa os dados e carrega para um banco de dados próprio.

Eu queria saber, qual horário que os dados são atualizados (despesas por ex, que tem atualização diária)? Para que eu possa ajustar o horário do meu cronjob para baixar os arquivos logo depois de serem atualizados. Atualmente estou rodando o cronjob todo dia ás 6 da manhã, mas observo algumas perdas em relação a API rest da câmara em despesas mais recentes.

Se puderem me informar em qual horário ocorre a atualização dos dados, seria de grande ajuda! 🙏

**Comment by EquipeDadosAbertosCD** [comment]
Olá, Victor!

Os arquivos para download são todos gerados durante a madrugada. Cada conjunto de dados é gerado em um horário diferente que normalmente vai de 1h30 a 5h30. Há variações ocasionais conforme serviços de manutenção de infraestrutura.

Os arquivos e o endpoint de despesas pela Cota Parlamentar são um pouco diferentes dos demais nesse aspecto. Os outros conjuntos são gerados por consultas feitas diretamente às bases que são utilizadas e alimentadas pelos sistemas internos da Câmara. Já os dados sobre despesas vêm de uma mesma tabela que é atualizada _também uma vez por dia_, feita por um ETL da área que cuida do sistema de Cotas Parlamentares.

É estranho, portanto, haver diferenças entre os arquivos e o endpoint. Se você tiver exemplos, por favor os envie por e-mail para dadosabertos.ditec@camara.leg.br .

Abraço e obrigado!

Fabricio Rocha
Equipe Dados Abertos - Câmara

**Comment by Victoreisdavid** [comment]
Obrigado pela resposta! Perdão pela demora.
