### ISSUE TITLE
Padronização do atributo 'siglaUF'

### ISSUE THREAD

**Issue by Allanbcruz** [CamaraDosDeputados/dados-abertos#342]
Poderiam padronizar o objeto 'siglaUF'?

na API abaixo com 'F' maiúsculo
.../deputados/{id}/historico
![Captura de Tela 2024-03-08 às 09 35 20](https://github.com/CamaraDosDeputados/dados-abertos/assets/57270969/d1945be3-b5d0-471a-bde4-4bb37c5d825b)

nas API's abaixo com 'f' minúsculo
.../deputados/{id}
![Captura de Tela 2024-03-08 às 09 37 24](https://github.com/CamaraDosDeputados/dados-abertos/assets/57270969/fcb9a95b-aab2-45a6-88c1-d6bc4c235c88)

.../eventos/{id}/deputados
![Captura de Tela 2024-03-08 às 09 38 14](https://github.com/CamaraDosDeputados/dados-abertos/assets/57270969/efb76633-6f72-4b5c-b52f-60a5dc4274f8)

**Comment by EquipeDadosAbertosCD** [comment]
Resolvido. Obrigado pelo alerta!

Fabricio Rocha
Equipe Dados Abertos - Câmara
