### ISSUE TITLE
Endpoint /eventos não retorna todos os eventos

### ISSUE THREAD

**Issue by cezzarCz** [CamaraDosDeputados/dados-abertos#350]
Estou implementando uma automação que utiliza o endpoint de /eventos para alimentar uma planilha.

Durante os testes reparei que os eventos, que não possuem um status (convocado, encerrada, em andamento, etc), não são retornados na requisição.

Exemplo de Requisição:
https://dadosabertos.camara.leg.br/api/v2/eventos?dataInicio=2024-06-21&dataFim=2024-06-21
Na página: https://www.camara.leg.br/agenda com os filtros de data aplicados, constam 8 eventos listados, 5 com status e 3 sem status (VISITAS GUIADAS e OUTROS EVENTOS). 
Ao fazer a requisição pelo endpoint citado acima, somente os 5 eventos com status são retornados.
XML retornado:
<xml>
<dados>
<evento_>
...
</evento_>
<evento_>
...
</evento_>
<evento_>
...
</evento_>
<evento_>
...
</evento_>
<evento_>
...
</evento_>
</dados>
<links>
<link>
<rel>self</rel>
<href>https://dadosabertos.camara.leg.br/api/v2/eventos?dataInicio=2024-06-21&dataFim=2024-06-21</href>
</link>
<link>
<rel>first</rel>
<href>https://dadosabertos.camara.leg.br/api/v2/eventos?dataInicio=2024-06-21&dataFim=2024-06-21&pagina=1&itens=15</href>
</link>
<link>
<rel>last</rel>
<href>https://dadosabertos.camara.leg.br/api/v2/eventos?dataInicio=2024-06-21&dataFim=2024-06-21&pagina=1&itens=15</href>
</link>
</links>
</xml>

**Comment by claudiodm** [comment]
Bom dia, cezzarCz.
Os eventos apresentados na API dadosAbertos são relativos ao processo legislativo. 
Palestras e visitas guiadas não fazem parte do processo.

**Comment by cezzarCz** [comment]
Certo, obrigado pela informação
